// خدمة العمل بلا إنترنت لتطبيق «قرية الخير» (مولّد بـ tests/gen-sw.mjs — لا تعدّله يدوياً)
// الاستراتيجية: الشبكة أولاً لكل الملفات (بلا ذاكرة المتصفح المؤقتة) فيصل كل تحديث فوراً؛ والمحفوظ فقط بلا إنترنت أو إن تأخرت الشبكة ٤ ثوانٍ.
const CACHE = 'qaryat-alkhair-094a6d98f5';
const FILES = ["./","./achievements/achievements.js","./achievements/badges.js","./assets/fonts/cairo-arabic-700-normal.woff2","./assets/fonts/cairo-arabic-900-normal.woff2","./assets/fonts/cairo-latin-700-normal.woff2","./assets/fonts/cairo-latin-900-normal.woff2","./assets/icons/apple-180.png","./assets/icons/icon-192.png","./assets/icons/icon-512.png","./assets/icons/maskable-512.png","./character/human.js","./content/chArt.js","./content/chData.js","./content/chGeo.js","./content/challenges1.js","./content/challenges2.js","./content/challenges3.js","./content/challenges4.js","./content/challenges5.js","./content/challenges6.js","./content/challenges7.js","./content/challenges8.js","./content/challenges9.js","./content/lessons.js","./content/outcomes.js","./core/engine.js","./core/events.js","./core/levels.js","./core/season.js","./core/sound.js","./core/state.js","./core/util.js","./lib/three/LICENSE","./lib/three/addons/BufferGeometryUtils.js","./lib/three/addons/CopyShader.js","./lib/three/addons/EffectComposer.js","./lib/three/addons/LuminosityHighPassShader.js","./lib/three/addons/MaskPass.js","./lib/three/addons/OutputPass.js","./lib/three/addons/OutputShader.js","./lib/three/addons/Pass.js","./lib/three/addons/RenderPass.js","./lib/three/addons/RoomEnvironment.js","./lib/three/addons/RoundedBoxGeometry.js","./lib/three/addons/ShaderPass.js","./lib/three/addons/UnrealBloomPass.js","./lib/three/three.core.min.js","./lib/three/three.module.min.js","./main.js","./manifest.webmanifest","./math/distribution.js","./missions/activity.js","./missions/bench.js","./missions/challenge.js","./missions/convoy.js","./missions/planting.js","./missions/quests.js","./missions/shop.js","./missions/t2u1.js","./missions/t2u2.js","./missions/t2u3.js","./missions/t2u4.js","./missions/t2u5.js","./missions/tanks.js","./missions/unit1.js","./missions/unit2.js","./missions/unit3.js","./missions/unit4.js","./npc/npc.js","./player/player.js","./renderer3d/city.js","./renderer3d/geom.js","./renderer3d/index.js","./renderer3d/nature.js","./renderer3d/omani.js","./renderer3d/people.js","./renderer3d/post.js","./renderer3d/preview.js","./renderer3d/props.js","./renderer3d/props2.js","./renderer3d/ramadan.js","./renderer3d/regions.js","./renderer3d/textures.js","./renderer3d/things.js","./renderer3d/world.js","./rewards/goodDeeds.js","./save/save.js","./story/dialogues.js","./style.css","./ui/home.css","./ui/home.js","./ui/hud.js","./ui/hudicons.js","./ui/modern.css","./ui/screens.js","./ui/wardrobe.js","./ui/worldmap.js","./world/art.js","./world/caravan.js","./world/coop.js","./world/decor.js","./world/entities.js","./world/festival.js","./world/fort.js","./world/harbor.js","./world/market.js","./world/nav.js","./world/pet.js","./world/school.js","./world/treasure.js","./world/village.js","./world/workshop.js","./index.html"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('qaryat-alkhair-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const r = e.request, u = new URL(r.url); if (r.method !== 'GET' || u.origin !== location.origin) return;
  const key = r.mode === 'navigate' ? './index.html' : r;
  e.respondWith(new Promise(done => {
    let settled = false; const finish = v => { if (!settled && v) { settled = true; done(v); } };
    const cached = () => caches.match(key, { ignoreSearch: true });
    fetch(new Request(r, { cache: 'no-cache' })).then(res => { if (res.ok) { const cp = res.clone(); caches.open(CACHE).then(c => c.put(key, cp)); } finish(res); })
      .catch(() => cached().then(hit => finish(hit || Response.error())));
    setTimeout(() => cached().then(hit => finish(hit)), 4000);   // شبكة بطيئة جداً: المحفوظ
  }));
});
