// خدمة العمل بلا إنترنت لتطبيق «قرية الخير» (مولّد بـ tests/gen-sw.mjs — لا تعدّله يدوياً)
// الاستراتيجية: كل الملفات تُحفظ عند التثبيت؛ الصفحة: الشبكة أولاً ثم المحفوظ؛ بقية الملفات: المحفوظ أولاً ويُحدَّث في الخلفية.
const CACHE = 'qaryat-alkhair-a69d4fdc4b';
const FILES = ["./","./achievements/achievements.js","./achievements/badges.js","./assets/fonts/cairo-arabic-700-normal.woff2","./assets/fonts/cairo-arabic-900-normal.woff2","./assets/fonts/cairo-latin-700-normal.woff2","./assets/fonts/cairo-latin-900-normal.woff2","./assets/icons/apple-180.png","./assets/icons/icon-192.png","./assets/icons/icon-512.png","./assets/icons/maskable-512.png","./character/human.js","./content/chArt.js","./content/chData.js","./content/chGeo.js","./content/challenges1.js","./content/challenges2.js","./content/challenges3.js","./content/challenges4.js","./content/challenges5.js","./content/challenges6.js","./content/challenges7.js","./content/challenges8.js","./content/challenges9.js","./content/lessons.js","./content/outcomes.js","./core/engine.js","./core/events.js","./core/levels.js","./core/season.js","./core/sound.js","./core/state.js","./core/util.js","./lib/three/LICENSE","./lib/three/addons/BufferGeometryUtils.js","./lib/three/addons/CopyShader.js","./lib/three/addons/EffectComposer.js","./lib/three/addons/LuminosityHighPassShader.js","./lib/three/addons/MaskPass.js","./lib/three/addons/OutputPass.js","./lib/three/addons/OutputShader.js","./lib/three/addons/Pass.js","./lib/three/addons/RenderPass.js","./lib/three/addons/RoomEnvironment.js","./lib/three/addons/RoundedBoxGeometry.js","./lib/three/addons/ShaderPass.js","./lib/three/addons/UnrealBloomPass.js","./lib/three/three.core.min.js","./lib/three/three.module.min.js","./main.js","./manifest.webmanifest","./math/distribution.js","./missions/activity.js","./missions/bench.js","./missions/challenge.js","./missions/convoy.js","./missions/planting.js","./missions/quests.js","./missions/shop.js","./missions/t2u1.js","./missions/t2u2.js","./missions/t2u3.js","./missions/t2u4.js","./missions/t2u5.js","./missions/tanks.js","./missions/unit1.js","./missions/unit2.js","./missions/unit3.js","./missions/unit4.js","./npc/npc.js","./player/player.js","./renderer3d/city.js","./renderer3d/geom.js","./renderer3d/index.js","./renderer3d/nature.js","./renderer3d/omani.js","./renderer3d/people.js","./renderer3d/post.js","./renderer3d/preview.js","./renderer3d/props.js","./renderer3d/props2.js","./renderer3d/ramadan.js","./renderer3d/regions.js","./renderer3d/textures.js","./renderer3d/things.js","./renderer3d/world.js","./rewards/goodDeeds.js","./save/save.js","./story/dialogues.js","./style.css","./ui/home.css","./ui/home.js","./ui/hud.js","./ui/hudicons.js","./ui/modern.css","./ui/screens.js","./ui/wardrobe.js","./ui/worldmap.js","./world/art.js","./world/caravan.js","./world/coop.js","./world/entities.js","./world/festival.js","./world/fort.js","./world/harbor.js","./world/market.js","./world/nav.js","./world/school.js","./world/village.js","./world/workshop.js","./index.html"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('qaryat-alkhair-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const r = e.request; if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  if (r.mode === 'navigate') { e.respondWith(fetch(r).then(res => { const cp = res.clone(); caches.open(CACHE).then(c => c.put('./index.html', cp)); return res; }).catch(() => caches.match('./index.html'))); return; }
  e.respondWith(caches.match(r, { ignoreSearch: true }).then(hit => { const net = fetch(r).then(res => { if (res.ok) { const cp = res.clone(); caches.open(CACHE).then(c => c.put(r, cp)); } return res; }).catch(() => hit); return hit || net; }));
});
