// اختبار «سر المدينة القديمة» كاملة بالنقر كاللاعب: node adv-oldcity.mjs [مجلد اللقطات] [--3d]
import { openAdventure, sleep } from './adv-lib.mjs';
const out = process.argv[2] && !process.argv[2].startsWith('--') ? process.argv[2] : null, d3 = process.argv.includes('--3d');
const T = await openAdventure('oldcity', { d3 }); const { ok, tap, go, tile, st, ev, shot } = T;
const pos = id => ev(id => { const e = window.__adv.ent(id); return e ? [e.x, e.y] : null; }, id);
const val = (id, k) => ev(([id, k]) => (window.__adv.ent(id) || {})[k], [id, k]);
await shot(out, 'oc-1');
ok('البداية في المدينة والهدف الأول', (await st()).area === 'city' && /ماجد/.test((await st()).goal), (await st()).goal);
await tap('majid'); ok('١. الحديث مع الجد ماجد', !!(await st()).flags.met);
await tile(16, 9); await sleep(300); ok('البوابة مغلقة قبل حل الألواح', !(await val('gate', 'open')));
await tap('c_hammer'); ok('٢. المطرقة', !!(await st()).inv.hammer);
await tap('f1'); ok('النقش الأول يحكي القصة', (await st()).inv.frag === 1);
const sting = await ev(async () => { const A = window.__adv, h = A.ent('sc1'); A.tp(Math.round(h.px), Math.round(h.py)); await new Promise(r => setTimeout(r, 2400)); return A.hero(); });
ok('العقرب يعيدك إلى نقطة آمنة', (sting.x === 3 && sting.y === 17) || (sting.x === 16 && sting.y === 14), JSON.stringify(sting));
await ev(() => { window.__adv.S.flags.invisible = 1; });
await go(21, 16); ok('النقش الثاني', (await st()).inv.frag === 2);
await go(22, 12); await tile(23, 12); ok('كسر الركام بالمطرقة', await ev(() => !!window.__adv.S.cut['city:23,12']));
await go(26, 11); await go(28, 13); ok('٣. النقش الثالث (والنجمة في الزاوية)', (await st()).inv.frag === 3);
await shot(out, 'oc-2');
const sol = { t1: 0, t2: 3, t3: 1 };
for (const t of ['t1', 't2', 't3']) for (let i = 0; i < 4 && (await val(t, 'sym')) !== sol[t]; i++) await tap(t);
await sleep(800); ok('٤. ألواح البوابة: الهلال والنخلة والشمس تفتح البوابة', !!(await st()).flags.gate && !!(await val('gate', 'open')));
await shot(out, 'oc-3');
for (const [x, y] of [[2, 10], [27, 17]]) await go(x, y);
await go(15, 0); await sleep(1500); await T.act('Promise.resolve()');
ok('٥. دخول القصر', (await st()).area === 'palace');
await shot(out, 'oc-4');
await ev(() => { window.__adv.S.flags.invisible = 1; });
await go(4, 7); await tile(4, 6); await tap('sara'); ok('٦. إنقاذ سارة ونصف القرص الأيسر', !!(await st()).flags.sara && !!(await st()).inv.keyB);
const want = { N: 0, S: 2, W: 3, E: 1 };
for (const s of ['N', 'S', 'W', 'E']) for (let i = 0; i < 4 && (await val(s, 'r')) !== want[s]; i++) await tap(s);
await sleep(800); ok('٧. التماثيل الأربعة نحو النافورة تفتح الخزانة', !!(await st()).flags.statues && !!(await val('vault', 'open')));
await shot(out, 'oc-5');
await tap('c_keyA'); ok('٨. نصف القرص الأيمن', !!(await st()).inv.keyA);
await tap('b1'); await sleep(500); await tap('b2'); await sleep(900);
ok('٩. الصندوقان على اللوحين يفتحان بوابة المعبد', !!(await st()).flags.plates && !!(await val('tgate', 'open')));
await shot(out, 'oc-6');
await go(27, 19); await go(15, 0); await sleep(1500); await T.act('Promise.resolve()');
ok('١٠. دخول المعبد', (await st()).area === 'temple');
await shot(out, 'oc-7');
const seen = await ev(async () => { const A = window.__adv, g = A.ent('guard'); delete A.S.flags.invisible; A.tp(Math.round(g.px) + 2, Math.round(g.py)); g.ang = 0; g.pause = 3; await new Promise(r => setTimeout(r, 2600)); return A.hero(); });
ok('الحارس الحجري يعيدك إلى مكان آمن (النار أو مدخل المعبد)', seen.x === 14 && (seen.y === 15 || seen.y === 16), JSON.stringify(seen));
await ev(() => { window.__adv.S.flags.invisible = 1; });
ok('الشعاع لا يصل في البداية', !(await val('cr', 'lit')));
const wantM = { m1: 1, m2: 1, m3: 2 };
for (const m of ['m1', 'm2', 'm3']) for (let i = 0; i < 4 && (await val(m, 'r')) !== wantM[m]; i++) await tap(m);
await sleep(800); ok('١١. المرايا الثلاث توصل النور إلى البلّورة وتفتح الحجرة', !!(await st()).flags.beam && !!(await val('sdoor', 'open')));
await shot(out, 'oc-8');
await go(25, 3);
await tap('altar'); await sleep(1500);
ok('١٢. المذبح: يشرق قرص الشمس وتنتهي المغامرة', !!(await T.page.$('.advEnd')));
ok('النجوم الخمس', /٥ من ٥/.test(await T.page.textContent('.advEnd').catch(() => '')), await T.page.textContent('.advEndStars').catch(() => ''));
await shot(out, 'oc-9');
await T.done();
